### ISSUE TITLE
RiotClientServices API

### ISSUE THREAD

**Issue by PermissionError** [RumbleMike/ValorantClientAPI#15]
Hi,

Through looking at the log files, I noticed that Valorant also sends REST requests to a 127.0.0.1:5xxxx address, ran by the Riot Client. This seems to handle the player's presence, party data etc. Are there any plans to document these routes?

They all require a Basic auth token (remoting-auth-token), which according to various config files should be in the CLI arguments of VALORANT.exe, but I could never find them for whatever reason.

**Comment by RumbleMike** [comment]
Indeed, it will come after the update on new endpoints.
