### ISSUE TITLE
INVALID_HEADERS

### ISSUE THREAD

**Issue by sndrjhlncgr** [RumbleMike/ValorantClientAPI#18]
why i keep getting INVALID_HEADERS?

**Comment by BobbyESP** [comment]
You need to add this header. Is a change in the riot API: 
`"X-Riot-ClientPlatform":"ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9"`

**Comment by BobbyESP** [comment]
You need to add this new header for every response that gives u INVALID_HEADERS. 

"X-Riot-ClientPlatform":"ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9"

**Comment by BobbyESP** [comment]
PD: All that in one line, sorry, GitHub Formats it bad.

**Comment by sndrjhlncgr** [comment]
oh thankyou so much brooo! godbless!

**Comment by BobbyESP** [comment]
Np dude :))
