### ISSUE TITLE
"Getting started" code in other languages

### ISSUE THREAD

**Issue by ARKEOLOGIST** [RumbleMike/ValorantClientAPI#4]
Currently, the docs only have a code sample in Python for the API call. I was wondering if support for more languages like JavaScript could be added in the future.

**Comment by RumbleMike** [comment]
Possibly, Currently i am planning on adding a C# variant for getting started.

**Comment by BobbyESP** [comment]
For JavaScript, by the moment, you can use Valorant.js (in GitHub) it's a library for js made with RumbleMike's API
