### ISSUE TITLE
2 identical requests [Competitive History, Player MMR]

### ISSUE THREAD

**Issue by woolfi20** [RumbleMike/ValorantClientAPI#5]
Hi, I want to see user statistics but the request that I make on the page [Click](https://github.com/RumbleMike/ValorantAPI/blob/master/Docs/PlayerMMR.md) gives a completely different data that is specified here [Click](https://github.com/RumbleMike/ValorantAPI/blob/master/Docs/CompetitiveHistory.md) what should I do?

**Comment by BobbyESP** [comment]
Idk lol. That is the same request. Is weired.

**Comment by tbitowt** [comment]
Any update according PlayerMMR endpoint? Looks like https://github.com/RumbleMike/ValorantAPI/blob/master/Docs/PlayerMMR.md page is invalid

**Comment by BobbyESP** [comment]
Is not valid?? Btw, when i do the request, it gives to me the same response as Competitive History

**Comment by tbitowt** [comment]
That's why I mentioned that. It's same endpoint. I think the one for PlayerMMR should have different endpoint. Do you know what should it be?

**Comment by RumbleMike** [comment]
This is my bad on my documentation, there will be a fix with the rewrite

**Comment by tbitowt** [comment]
@RumbleMike could you post the correct endpoint here, just to speedup my work (if it's not too much work to do for you)
